/**
 * Reference-goods dataset — wave 1 (part A: food, agri, livestock, detergents).
 * Names speak the wholesale-market dialect of Iran (بنکدار زبان), English
 * comes from trade documents, not dictionaries. Aliases add local variants.
 */

export interface GoodSeed {
  n: string; // Persian canonical name (wholesale dialect)
  e?: string; // English trade name
  a?: string[]; // aliases (any language)
  u?: string; // unit override (defaults to the leaf's unit)
  p?: boolean; // PROVISIONAL — admin review queue (default: ACTIVE)
}

export const GOODS_A: Record<string, GoodSeed[]> = {
  // ── food ──────────────────────────────────────────────────────────────
  rice: [
    { n: "برنج هاشمی", e: "Hashemi rice", a: ["هاشمی"] },
    { n: "برنج طارم عطری", e: "Tarom rice", a: ["طارم"] },
    { n: "برنج دم سیاه", e: "Dom-siah rice", a: ["دمسیاه"] },
    { n: "برنج گرده", e: "Gerdah rice" },
    { n: "برنج برد", e: "Bard rice", a: ["برد هندی"] },
    { n: "برنج هندی ۱۱۲۱", e: "Indian 1121 rice", a: ["۱۱۲۱"] },
    { n: "برنج پاکستانی سوپر", e: "Pakistani super rice" },
    { n: "برنج شکسته", e: "Broken rice", a: ["گرجل"] },
  ],
  legumes: [
    { n: "لوبیا چیتی", e: "Chiti beans", a: ["چیتی"] },
    { n: "لوبیا قرمز", e: "Red beans" },
    { n: "لوبیا سفید", e: "White beans" },
    { n: "نخود", e: "Chickpeas", a: ["نخود آباده"] },
    { n: "عدس", e: "Lentils" },
    { n: "ماش", e: "Mung beans" },
    { n: "لپه", e: "Split peas" },
    { n: "باقالی", e: "Fava beans", a: ["باقلا"] },
  ],
  "flour-cereals": [
    { n: "آرد گندم", e: "Wheat flour", a: ["آرد"] },
    { n: "آرد نانوایی", e: "Bakery flour", a: ["آرد سنگ‌تک"] },
    { n: "آرد سفید", e: "White flour" },
    { n: "آرد ذرت", e: "Corn flour" },
    { n: "جو دوسر", e: "Oats", a: ["جو پرک"] },
    { n: "بلغور گندم", e: "Bulgur wheat" },
    { n: "سمولینا", e: "Semolina" },
    { n: "سبوس گندم", e: "Wheat bran" },
  ],
  "dried-fruit": [
    { n: "پسته اکبری", e: "Akbari pistachio", a: ["اکبری"] },
    { n: "پسته احمدآقایی", e: "Ahmadaghaei pistachio" },
    { n: "پسته فندقی", e: "Fandoghi pistachio" },
    { n: "پسته کله‌قوچی", e: "Kallehghouchi pistachio" },
    { n: "پسته دهن‌باز", e: "Open-mouth pistachio" },
    { n: "کشمش تیزابی", e: "Golden raisins", a: ["کشمش"] },
    { n: "کشمش پلویی", e: "Sun-dried raisins" },
    { n: "کشمش ملایر", e: "Malayer raisins" },
    { n: "خرمای مضافتی", e: "Mazafati dates", a: ["مضافتی", "خرما"] },
    { n: "خرمای پیارم", e: "Piarom dates", a: ["پیارم"] },
    { n: "خرمای خازویی", e: "Khazaei dates" },
    { n: "خرمای کبکاب", e: "Kabkab dates" },
    { n: "خرمای زاهدی", e: "Zahedi dates" },
    { n: "مغز گردو", e: "Walnut kernels", a: ["گردو"] },
    { n: "مغز بادام", e: "Almond kernels", a: ["بادام"] },
    { n: "بادام زمینی", e: "Peanuts" },
    { n: "فندق", e: "Hazelnuts" },
    { n: "تخمه ژاپنی", e: "Japanese sunflower seeds", a: ["تخمه"] },
    { n: "تخمه آفتابگردان", e: "Sunflower seeds" },
    { n: "بادام هندی", e: "Cashews" },
  ],
  "fresh-produce": [
    { n: "پیاز", e: "Onion" },
    { n: "سیب‌زمینی", e: "Potato", a: ["سیب زمینی"] },
    { n: "گوجه‌فرنگی", e: "Tomato", a: ["گوجه"] },
    { n: "خیار گلخانه‌ای", e: "Greenhouse cucumber", a: ["خیار"] },
    { n: "سیب قرمز", e: "Red apple", a: ["سیب"] },
    { n: "پرتقال تامسون", e: "Thomson orange", a: ["پرتقال"] },
    { n: "نارنگی", e: "Tangerine" },
    { n: "انار", e: "Pomegranate" },
    { n: "هویج", e: "Carrot" },
    { n: "کلم بروکلی", e: "Broccoli" },
    { n: "لیمو ترش", e: "Lime" },
  ],
  oils: [
    { n: "روغن نباتی مایع", e: "Liquid vegetable oil", a: ["روغن سرخ‌کردنی", "روغن"] },
    { n: "روغن سرخ‌کردنی", e: "Frying oil" },
    { n: "روغن آفتابگردان", e: "Sunflower oil" },
    { n: "روغن ذرت", e: "Corn oil" },
    { n: "روغن زیتون", e: "Olive oil" },
    { n: "روغن کانولا", e: "Canola oil" },
    { n: "کره نباتی", e: "Vegetable ghee" },
    { n: "مارگارین", e: "Margarine" },
    { n: "عسل طبیعی", e: "Natural honey", a: ["عسل"] },
  ],
  dairy: [
    { n: "ماست", e: "Yogurt" },
    { n: "ماست موسیر", e: "Musir yogurt" },
    { n: "پنیر سفید", e: "White cheese", a: ["پنیر"] },
    { n: "پنیر لیقوان", e: "Lighvan cheese" },
    { n: "شیر پاستوریزه", e: "Pasteurized milk", a: ["شیر"] },
    { n: "شیرخشک", e: "Milk powder" },
    { n: "کره حیوانی", e: "Butter", a: ["کره"] },
    { n: "خامه", e: "Cream" },
    { n: "دوغ", e: "Doogh" },
  ],
  "protein-canned": [
    { n: "تون ماهی", e: "Canned tuna", a: ["تن ماهی", "تُن"] },
    { n: "کنسرو لوبیا", e: "Canned beans" },
    { n: "گوشت گوسفندی", e: "Sheep meat", a: ["گوشت گوسفند"] },
    { n: "گوشت گوساله", e: "Beef", a: ["گوشت گاو"] },
    { n: "مرغ کشتار", e: "Slaughtered chicken", a: ["مرغ"] },
    { n: "فیله مرغ", e: "Chicken fillet" },
    { n: "سوسیس", e: "Sausage" },
    { n: "کالباس", e: "Bologna" },
    { n: "ماهی منجمد", e: "Frozen fish" },
    { n: "میگو", e: "Shrimp" },
  ],
  "sugar-tea": [
    { n: "شکر", e: "Sugar" },
    { n: "قند", e: "Sugar loaf", a: ["حبه قند"] },
    { n: "نبات", e: "Rock candy", a: ["نبات کبریتی"] },
    { n: "چای سیاه", e: "Black tea", a: ["چای"] },
    { n: "چای شکسته", e: "Broken tea" },
    { n: "چای کیسه‌ای", e: "Tea bags" },
    { n: "قهوه فوری", e: "Instant coffee", a: ["نسکافه"] },
    { n: "قهوه اسپرسو", e: "Espresso coffee" },
  ],
  "spices-saffron": [
    { n: "زعفران سرگل", e: "Sargol saffron", a: ["زعفران"] },
    { n: "زعفران نگین", e: "Negin saffron" },
    { n: "زعفران پوشال", e: "Pushal saffron" },
    { n: "زردچوبه", e: "Turmeric" },
    { n: "دارچین", e: "Cinnamon" },
    { n: "فلفل سیاه", e: "Black pepper" },
    { n: "پاپریکا", e: "Paprika" },
    { n: "ادویه پلویی", e: "Rice spice mix" },
    { n: "هل", e: "Cardamom" },
    { n: "گلاب قمصر", e: "Ghamsar rosewater", a: ["گلاب"] },
    { n: "عرق نعنا", e: "Mint distillate", a: ["عرقیات"] },
  ],
  "snacks-sweets": [
    { n: "چیپس سیب‌زمینی", e: "Potato chips", a: ["چیپس"] },
    { n: "پفک", e: "Cheese puffs" },
    { n: "بیسکویت", e: "Biscuits" },
    { n: "ویفر", e: "Wafer" },
    { n: "شکلات", e: "Chocolate" },
    { n: "آبنبات", e: "Candy" },
    { n: "تافی", e: "Toffee" },
    { n: "پاستیل", e: "Gummy candy" },
    { n: "آدامس", e: "Chewing gum" },
    { n: "کیک یزدی", e: "Yazdi cake" },
    { n: "کیک شطرنجی", e: "Checkerboard cake" },
    { n: "کیک هویج", e: "Carrot cake" },
    { n: "کیک پرتقالی", e: "Orange cake" },
    { n: "کلوچه کشمشی", e: "Raisin cookies" },
    { n: "بستنی فله‌ای", e: "Bulk ice cream" },
  ],
  "prepared-food": [
    { n: "رب گوجه‌فرنگی", e: "Tomato paste", a: ["رب"] },
    { n: "ماکارونی", e: "Macaroni", a: ["پاستا"] },
    { n: "ماکارونی فرمی", e: "Fusilli pasta" },
    { n: "سس مایونز", e: "Mayonnaise" },
    { n: "سس کچاپ", e: "Ketchup" },
    { n: "سس سویا", e: "Soy sauce" },
    { n: "کنسرو ذرت", e: "Canned corn" },
    { n: "کنسرو نخودفرنگی", e: "Canned peas" },
    { n: "مربا", e: "Jam" },
    { n: "ترشی و خیارشور", e: "Pickles" },
    { n: "غذای کنسروی", e: "Canned meals" },
  ],
  beverages: [
    { n: "نوشابه", e: "Soft drink" },
    { n: "آب معدنی", e: "Mineral water" },
    { n: "آبمیوه", e: "Fruit juice" },
    { n: "نوشیدنی مالت", e: "Malt beverage" },
    { n: "نوشیدنی انرژی‌زا", e: "Energy drink" },
    { n: "چای سرد", e: "Iced tea" },
  ],
  "food-additives": [
    { n: "پودر کاکائو", e: "Cocoa powder" },
    { n: "اسید سیتریک", e: "Citric acid" },
    { n: "رنگ خوراکی", e: "Food coloring" },
    { n: "وانیل", e: "Vanilla" },
    { n: "بکینگ پودر", e: "Baking powder" },
    { n: "مایه خمیر", e: "Yeast", a: ["خمیرمایه"] },
    { n: "ژلاتین", e: "Gelatin" },
    { n: "نشاسته", e: "Starch" },
  ],

  // ── agri ──────────────────────────────────────────────────────────────
  fertilizers: [
    { n: "کود اوره", e: "Urea fertilizer", a: ["اوره"] },
    { n: "کود فسفاته", e: "Phosphate fertilizer" },
    { n: "کود پتاسه", e: "Potash fertilizer" },
    { n: "کود NPK", e: "NPK fertilizer" },
    { n: "کود آلی", e: "Organic fertilizer" },
    { n: "کود مایع", e: "Liquid fertilizer" },
  ],
  "seeds-plants": [
    { n: "بذر گوجه‌فرنگی", e: "Tomato seeds", a: ["بذر"] },
    { n: "بذر خیار", e: "Cucumber seeds" },
    { n: "بذر فلفل", e: "Pepper seeds" },
    { n: "بذر ذرت علوفه‌ای", e: "Forage corn seeds" },
    { n: "نهال سیب", e: "Apple sapling", a: ["نهال"] },
    { n: "نهال گردو", e: "Walnut sapling" },
    { n: "نهال انگور", e: "Grape sapling" },
    { n: "نشاء گلخانه‌ای", e: "Greenhouse seedlings", a: ["نشاء"] },
  ],
  pesticides: [
    { n: "علف‌کش", e: "Herbicide" },
    { n: "حشره‌کش", e: "Insecticide" },
    { n: "قارچ‌کش", e: "Fungicide" },
    { n: "کنه‌کش", e: "Acaricide" },
    { n: "سم عمومی", e: "General pesticide" },
  ],
  greenhouse: [
    { n: "پلاستیک گلخانه", e: "Greenhouse plastic film" },
    { n: "نوار آبیاری قطره‌ای", e: "Drip irrigation tape", a: ["تیپ"] },
    { n: "لوله آبیاری", e: "Irrigation pipe" },
    { n: "توری سایه‌بان", e: "Shade net" },
    { n: "کوکوپیت", e: "Cocopeat" },
  ],

  // ── livestock ─────────────────────────────────────────────────────────
  "animal-feed": [
    { n: "کنسانتره دام", e: "Cattle concentrate", a: ["کنسانتره"] },
    { n: "کنسانتره طیور", e: "Poultry concentrate" },
    { n: "کنجاله سویا", e: "Soybean meal", a: ["کنجاله"] },
    { n: "ذرت دامی", e: "Feed corn" },
    { n: "جو دامی", e: "Feed barley" },
    { n: "مکمل دامی", e: "Feed supplement" },
    { n: "ویتامین دامی", e: "Animal vitamins" },
    { n: "کلسیم دامی", e: "Animal calcium" },
  ],
  forage: [
    { n: "یونجه فشرده", e: "Compressed alfalfa", a: ["یونجه"] },
    { n: "یونجه پرس‌شده", e: "Baled alfalfa" },
    { n: "کاه و کلش", e: "Straw" },
  ],
  "live-animals": [
    { n: "گوسفند زنده", e: "Live sheep", a: ["گوسفند"] },
    { n: "گاو نر زنده", e: "Live bull", a: ["گاو"] },
    { n: "گوساله زنده", e: "Live calf" },
    { n: "بز زنده", e: "Live goat" },
  ],
  "poultry-eggs": [
    { n: "مرغ گرم", e: "Fresh broiler chicken", a: ["مرغ"] },
    { n: "مرغ منجمد", e: "Frozen chicken" },
    { n: "جوجه یک‌روزه", e: "Day-old chick" },
    { n: "تخم‌مرغ", e: "Eggs", a: ["تخم مرغ"] },
    { n: "تخم‌مرغ بومی", e: "Free-range eggs" },
  ],
  aquaculture: [
    { n: "قزل‌آلا", e: "Rainbow trout" },
    { n: "بچه‌ماهی قزل‌آلا", e: "Trout fingerlings" },
    { n: "میگو پرورشی", e: "Farmed shrimp" },
    { n: "ماهی خاویاری", e: "Sturgeon" },
    { n: "خاویار", e: "Caviar" },
  ],

  // ── detergents ────────────────────────────────────────────────────────
  "home-cleaning": [
    { n: "مایع ظرفشویی", e: "Dishwashing liquid", a: ["ظرفشویی"] },
    { n: "پودر لباسشویی", e: "Laundry powder", a: ["پودر"] },
    { n: "مایع لباسشویی", e: "Liquid laundry detergent" },
    { n: "مایع دستشویی", e: "Handwash liquid" },
    { n: "وایتکس", e: "Bleach", a: ["آب ژاول"] },
    { n: "جرم‌گیر", e: "Drain cleaner" },
    { n: "مایع شیشه‌پاک", e: "Glass cleaner" },
    { n: "کارواش بدنه خودرو", e: "Car wash shampoo" },
  ],
  tissue: [
    { n: "دستمال کاغذی", e: "Facial tissue", a: ["دستمال"] },
    { n: "دستمال توالت", e: "Toilet paper" },
    { n: "رول آشپزخانه", e: "Kitchen towel roll" },
    { n: "دستمال مرطوب", e: "Wet wipes" },
    { n: "دستمال حوله‌ای", e: "Paper towels" },
  ],
  "baby-care": [
    { n: "پوشک بچه", e: "Baby diaper", a: ["پوشک"] },
    { n: "شامپو بچه", e: "Baby shampoo" },
    { n: "دستمال کودک", e: "Baby wipes" },
  ],
  "personal-care": [
    { n: "شامپو مو", e: "Hair shampoo", a: ["شامپو"] },
    { n: "صابون حمام", e: "Bath soap", a: ["صابون"] },
    { n: "صابون رختشویی", e: "Laundry bar soap" },
    { n: "خمیر دندان", e: "Toothpaste" },
    { n: "مسواک", e: "Toothbrush" },
    { n: "اسپری خوشبوکننده", e: "Body spray" },
    { n: "ژله روغنی", e: "Petroleum jelly" },
  ],
  cosmetics: [
    { n: "کرم مرطوب‌کننده", e: "Moisturizing cream" },
    { n: "کرم ضدآفتاب", e: "Sunscreen" },
    { n: "کرم پودر", e: "Foundation cream" },
    { n: "رژ لب", e: "Lipstick" },
    { n: "ریمل", e: "Mascara" },
    { n: "لاک ناخن", e: "Nail polish" },
  ],
};
