/**
 * Category mapping: barcodeapp category → iMach category slug.
 *
 * Each mapping returns:
 *   { slug: "iMach-slug", unit: "default-unit" }
 *
 * When a barcodeapp category doesn't have a perfect match in iMach,
 * we fall back to the closest equivalent.
 */

const BC_TO_IMACH = {
  // ─── FOOD: خوراکی‌ها ───
  // Sweets & desserts
  "شیرینی و دسر": "snacks-sweets",
  "بیسکویت، کیک، شکلات و ادامس": "snacks-sweets",
  "شکلات": "snacks-sweets",
  "شکلات صبحانه": "snacks-sweets",
  "شکلات کادویی": "snacks-sweets",
  "دسر": "snacks-sweets",
  "بستنی": "snacks-sweets",
  "بستنی و فالوده": "snacks-sweets",
  "پودر کیک": "snacks-sweets",
  "مواد کیک و شیرینی پزی": "snacks-sweets",
  "حلوا": "snacks-sweets",
  "ارده": "snacks-sweets",
  "عسل ، مربا و حلوا شکری": "snacks-sweets",
  "عسل": "snacks-sweets",

  // Snacks
  "تنقلات": "snacks-sweets",
  "چیپس": "snacks-sweets",
  "اسنک": "snacks-sweets",
  "پفک و اسنک پنیری": "snacks-sweets",
  "پاپ کورن": "snacks-sweets",
  "پاپ کرن": "snacks-sweets",
  "پشمک": "snacks-sweets",
  "تافی و آبنبات": "snacks-sweets",
  "پاستیل": "snacks-sweets",
  "آدامس": "snacks-sweets",
  "تنقلات ترش": "snacks-sweets",
  "بسکویت، ویفر": "snacks-sweets",
  "اسمارتیز": "snacks-sweets",
  "شکرپنیر": "snacks-sweets",
  "کیک، کلوچه": "snacks-sweets",
  "نی شیر": "snacks-sweets",
  "چوب شور": "snacks-sweets",
  "لواشک و آلوچه": "snacks-sweets",
  "لواشک، ترشک، آلوچه": "snacks-sweets",
  "تخمه": "snacks-sweets",
  "بادام زمینی": "snacks-sweets",
  "کره بادام زمینی": "snacks-sweets",
  "آجیل مخلوط": "snacks-sweets",
  "سایر آجیل ها": "snacks-sweets",
  "خشکبار و آجیل بسته ای": "snacks-sweets",

  // Dried fruit & nuts
  "خشکبار": "dried-fruit",
  "زرشک": "dried-fruit",
  "سبزیجات خشک": "dried-fruit",
  "گردو،کشمش،خلال،آلو": "dried-fruit",

  // Dairy
  "لبنیات": "dairy",
  "شیر": "dairy",
  "ماست": "dairy",
  "پنیر": "dairy",
  "دوغ": "dairy",
  "خامه": "dairy",
  "کره": "dairy",
  "کشک": "dairy",

  // Bread, cereals, grains
  "نان و غلات": "flour-cereals",
  "نان": "flour-cereals",
  "انواع نان": "flour-cereals",
  "آرد، خمیر، غلات": "flour-cereals",
  "انواع آردها": "flour-cereals",
  "انواع پودر و آرد سوخاری": "flour-cereals",
  "خمیرهای نیمه آماده": "bread-dough",
  "کرن فلکس و غلات صبحانه": "flour-cereals",
  "کورن فلکس": "flour-cereals",

  // Pasta, noodles
  "پاستا": "flour-cereals",
  "ماکارونی": "flour-cereals",
  "پاستا و نودل": "flour-cereals",
  "نودل": "flour-cereals",
  "رشته": "flour-cereals",
  "لازانیا": "flour-cereals",

  // Rice
  "برنج": "rice",

  // Legumes
  "حبوبات": "legumes",
  "حبوبات و غلات": "legumes",

  // Sugar, tea
  "قند ، شکر و نبات": "sugar-tea",
  "قند و شکر": "sugar-tea",
  "قند": "sugar-tea",
  "شکر": "sugar-tea",
  "چای ، دمنوش و قهوه": "sugar-tea",
  "چای": "sugar-tea",
  "دمنوش": "sugar-tea",

  // Spices, saffron
  "ادویه و چاشنی": "spices-saffron",
  "ادویه جات و نمک": "spices-saffron",
  "ادویه و چاشنی و مخلفات غذا": "spices-saffron",
  "سس‌ها، ادویه‌ها و چاشنی‌ها": "spices-saffron",
  "زعفران": "spices-saffron",
  "نمک": "spices-saffron",
  "زیتون": "spices-saffron",

  // Sauces, pastes, prepared food
  "سس": "prepared-food",
  "رب": "prepared-food",
  "رب گوجه فرنگی": "prepared-food",
  "سرکه": "prepared-food",
  "آبلیمو": "prepared-food",
  "آبلیمو ، آبغوره و سرکه": "prepared-food",
  "آبغوره": "prepared-food",
  "لیمو عمانی": "prepared-food",
  "مخلفات همراه غذا": "prepared-food",
  "خوراکی های اساسی": "prepared-food",
  "خواربار": "prepared-food",
  "پخت و پز": "prepared-food",
  "ترشی ها و شوری ها": "prepared-food",
  "ترشی": "prepared-food",
  "خیارشور": "prepared-food",

  // Food & canned
  "غذا و کنسرو": "protein-canned",
  "کنسرو": "protein-canned",
  "غذای نیمه آماده": "protein-canned",
  "غذای آماده": "protein-canned",
  "غذاهای آماده و نیمه آماده": "protein-canned",
  "سوپ، حلیم، آش آماده": "protein-canned",
  "مخصوص سوپ": "protein-canned",
  "ساندویچ": "protein-canned",
  "کلاب، ساندویچ، سالاد, پیتزا": "protein-canned",
  "سبزیجات": "fresh-produce",
  "سالادها": "fresh-produce",
  "کمپوت": "fresh-produce",
  "انواع کمپوت": "fresh-produce",

  // Protein
  "پروتئینی": "protein-canned",
  "فرآورده های پروتئینی": "protein-canned",
  "گوشت سفید": "protein-canned",
  "گوشت قرمز": "protein-canned",
  "گوشت مرغ": "protein-canned",
  "سوسیس و کالباس": "protein-canned",
  "تن ماهی": "protein-canned",

  // Oils
  "روغن": "oils",
  "روغن زیتون": "oils",
  "روغن مایع": "oils",
  "روغن جامد": "oils",

  // Beverages
  "نوشیدنی": "beverages",
  "نوشابه ، آب‌میوه و دلستر": "beverages",
  "نوشیدنی‌ های سرد": "beverages",
  "نوشیدنی های گرم": "beverages",
  "آب معدنی و عرقیات": "beverages",
  "آب": "beverages",
  "دلستر، ماءالشعیر": "beverages",
  "آب میوه گازدار": "beverages",
  "انرژی زا": "beverages",
  "شربت": "beverages",
  "عرقیات گیاهی": "beverages",

  // Food additives, supplements
  "افزودنی خوراکی": "food-additives",
  "خوراکی های اساسی": "food-additives",
  "مکمل غذایی کودک": "food-additives",
  "مواد غذایی کودک": "food-additives",
  "سلامت": "food-additives",

  // ─── DETERGENTS, PERSONAL CARE ───
  // Cleaning
  "شوینده و بهداشتی": "home-cleaning",
  "شوینده‌ها و نظافت منزل": "home-cleaning",
  "نظافت منزل": "home-cleaning",
  "نظافت خانه": "home-cleaning",
  "شست وشو لباس": "home-cleaning",
  "شوینده لباس": "home-cleaning",
  "شوینده لباس کودک": "home-cleaning",
  "مایع ظرفشویی": "home-cleaning",
  "وسایل شست و شوی ظروف": "home-cleaning",
  "اسکاج و سیم ظرفشویی": "home-cleaning",
  "پاک کننده سطوح و جرمگیر": "home-cleaning",
  "پاک‌کننده‌های سطوح و جرم‌گیر": "home-cleaning",
  "شیشه پاک کن": "home-cleaning",
  "سفید کننده": "home-cleaning",
  "نرم کننده": "home-cleaning",
  "شامپو فرش": "home-cleaning",
  "مواد مصرفی ماشین ظرفشویی": "home-cleaning",
  "مایع دستشویی": "home-cleaning",
  "صابون و مایع دستشویی": "home-cleaning",
  "صابون و فوم دستشویی": "home-cleaning",
  "مایع دستشویی-مردانه": "home-cleaning",

  // Tissue, paper
  "دستمال کاغذی": "tissue",
  "دستمال رولی": "tissue",
  "دستمال مرطوب": "tissue",
  "دستمال مرطوب کودک": "tissue",
  "پنبه و دستمال های کاغذی و بهداشتی": "tissue",
  "دستمال و دستکش": "tissue",

  // Pest control, hygiene
  "حشره‌کش، خوشبوکننده و بهداشت محیط": "home-cleaning",
  "حشره کش": "home-cleaning",
  "ضد عفونی کننده": "home-cleaning",

  // Bags, films
  "انواع کیسه و نایلون": "films-nylons",

  // Personal care
  "بهداشت شخصی": "personal-care",
  "بهداشت شخصی و استحمام": "personal-care",
  "بهداشت دهان و دندان": "personal-care",
  "انواع شامپو": "personal-care",
  "بهداشت و مراقبت از مو": "personal-care",
  "بهداشت و مراقبت از بدن": "personal-care",
  "تقویت کننده مو-زنانه": "personal-care",
  "ماسک مو": "personal-care",
  "نرم کننده مو-زنانه": "personal-care",
  "ژل مو-مردانه": "personal-care",
  "ژل مو-زنانه": "personal-care",
  "روغن بدن": "personal-care",
  "مسواک": "personal-care",
  "خمیر دندان": "personal-care",
  "دهانشویه": "personal-care",
  "نخ دندان": "personal-care",
  "خوشبو کننده دهان": "personal-care",
  "اصلاح": "personal-care",
  "ژل و فوم اصلاح- مردانه": "personal-care",
  "اصلاح سر و صورت آقایان": "personal-care",
  "ژل شستشو مردانه": "personal-care",
  "اسپری": "personal-care",
  "عطر و ادکلن": "personal-care",
  "ضد آفتاب": "personal-care",
  "وازلین": "personal-care",
  "حمام و سرویس بهداشتی": "personal-care",
  "کاور توالت فرنگی": "personal-care",

  // Cosmetics
  "آرایشی و بهداشتی": "cosmetics",
  "بهداشت": "cosmetics",
  "مراقبت": "cosmetics",
  "مراقبت پوست": "cosmetics",
  "کرم و لوسین": "cosmetics",
  "کرم روشن کننده": "cosmetics",
  "کرم دور چشم زنانه": "cosmetics",
  "ماسک صورت": "cosmetics",
  "لایه بردار": "cosmetics",
  "اسکراب": "cosmetics",
  "مراقبت لب": "cosmetics",
  "برنز کننده بدن": "cosmetics",
  "کرم مرطوب کننده-مردانه": "cosmetics",
  "کرم شب": "cosmetics",
  "کرم ضد آفتاب-مردانه": "cosmetics",
  "ژل ضد جوش زنانه": "cosmetics",
  "لوسیون بدن-زنانه": "cosmetics",
  "آرایش مو": "cosmetics",
  "رنگ مو و ملزومات": "cosmetics",
  "آرایش صورت": "cosmetics",
  "آرایش ناخن": "cosmetics",
  "لوازم آرایشی": "cosmetics",
  "ابزار جانبی آرایش مو": "cosmetics",
  "برس مو": "cosmetics",
  "بهداشت بانوان و لوازم آرایشی و بهداشتی": "cosmetics",
  "بهداشتی بانوان": "cosmetics",
  "بهداشت و مراقبت از بانوان": "cosmetics",
  "بهداشت و مراقبت مردان": "cosmetics",
  "مردانه": "cosmetics",
  "محصولات ارتودنسی": "cosmetics",

  // Baby care
  "بچگانه": "baby-care",
  "پوشک، بهداشت و استحمام کودک": "baby-care",
  "کرم و لوسیون کودک": "baby-care",
  "شامپو مو-بچگانه": "baby-care",
  "خمیر دندان-بچگانه": "baby-care",
  "مسواک-بچگانه": "baby-care",
  "ضد آفتاب کودک": "baby-care",
  "صابون کودک": "baby-care",
  "بهداشت بانوان": "cosmetics",

  // ─── Tools, kitchen ───
  "ابزار و ملزومات": "hand-tools",
  "ابزارهای خانه و آشپزخانه": "cookware",
  "ابزارهای الکترونیکی و لوازم جانبی": "computer-network",
  "وسايل برقی": "kitchen-electric",
  "وسايل غیر برقی": "cookware",
  "ملزومات خانه": "cookware",
  "باشگاه مشتریان": "jadid",
  "جوراب": "garments",
  "دستکش و جوراب": "garments",
  "قارچ": "fresh-produce",
  "ژله": "snacks-sweets",

  // ─── source_taxonomy categories (parent level) ───
  // These appear in metadata.source_taxonomy.category
  "تنقلات": "snacks-sweets",
  "آرایشی و بهداشتی": "cosmetics",
  "نوشیدنی": "beverages",
  "دستمال و شوینده": "home-cleaning",
  "چاشنی و افزودنی": "spices-saffron",
  "لبنیات و بستنی": "dairy",
  "کنسرو، غذای آماده و منجمد": "protein-canned",
  "خواربار و نان": "flour-cereals",
  "خانه و سبک زندگی": "home-furniture",
  "صبحانه": "snacks-sweets",
  "خشکبار، دسر و شیرینی": "snacks-sweets",
  "دخانیات": "snacks-sweets",
  "پروتئین و تخم مرغ": "protein-canned",
  "کودک و نوزاد": "baby-care",
  "روشنایی و الکترونیکی": "lighting",
  "پت شاپ": "animal-feed",
  "میوه و سبزیجات تازه": "fresh-produce",
  "مد و پوشاک": "garments",

  // ─── More category mappings (from jadid samples) ───
  "زغال و دخانیات": "snacks-sweets",
  "توتون و تنباکو": "snacks-sweets",
  "دخانیات": "snacks-sweets",
  "زغال": "snacks-sweets",
  "زیبایی و سلامت": "cosmetics",
  "مراقبت پوست و مو": "personal-care",
  "خوراک دام و طیور": "animal-feed",
  "خوراک حیوانات": "animal-feed",
  "پت": "animal-feed",
  "حیوانات خانگی": "animal-feed",
  "ملزومات حیوانات خانگی": "animal-feed",
  "اسباب بازی": "toys",
  "اسباب‌بازی": "toys",
  "ورزش": "sports-equip",
  "تجهیزات ورزشی": "sports-equip",
  "لوازم ورزشی": "sports-equip",
  "لوازم تحریر": "stationery",
  "نوشت‌افزار": "stationery",
  "کاغذ و دفتر": "paper-books",
  "لوازم التحریر": "stationery",
  "لوازم اداری": "office-consumables",
  "مصرفی اداری": "office-consumables",
  "کامپیوتر": "computer-network",
  "موبایل": "mobile-accessories",
  "گوشی موبایل": "mobile-accessories",
  "لوازم جانبی موبایل": "mobile-accessories",
  "لوازم برقی": "kitchen-electric",
  "لوازم خانگی": "major-appliances",
  "آشپزخانه": "cookware",
  "ظروف آشپزخانه": "cookware",
  "ملزومات آشپزخانه": "cookware",
  "لوازم چوبی": "home-furniture",
  "مبلمان": "home-furniture",
  "دکوراسیون": "decor",
  "تزئینات": "decor",
  "لوازم دکوری": "decor",
  "فرش": "carpets-rugs",
  "فرش و قالی": "carpets-rugs",
  "پوشاک": "garments",
  "لباس": "garments",
  "پارچه": "fabrics",
  "کیف و کفش": "shoes",
  "کفش و چرم": "shoes",
  "لوازم خودرو": "spare-parts",
  "قطعات خودرو": "spare-parts",
  "لوازم یدکی": "spare-parts",
  "لوازم ساختمانی": "cement-plaster",
  "مصالح ساختمانی": "cement-plaster",
  "لوازم پزشکی": "medical-equip",
  "تجهیزات پزشکی": "medical-equip",
  "لوازم آزمایشگاهی": "lab-equip",
  "تجهیزات آزمایشگاهی": "lab-equip",
  "ابزار": "hand-tools",
  "ابزار و یراق": "hand-tools",
  "ابزار و ملزومات": "hand-tools",
  "لوازم برقی": "lighting",
  "روشنایی": "lighting",
  "لامپ": "lighting",
  "لوازم روشنایی": "lighting",
  "کابل و سیم": "wires-cables",
  "سیم و کابل": "wires-cables",
  "لوازم الکتریکی": "switchgear",
  "کلید و پریز": "switchgear",
  "تابلو برق": "switchgear",
  "باتری": "batteries-power",
  "انرژی": "batteries-power",
  "لوازم باتری": "batteries-power",
  "آهن آلات": "steel-sections",
  "فلزات": "non-ferrous",
  "مقاطع فولادی": "steel-sections",
  "ضایعات فلزی": "scrap-metal",
  "ضایعات": "scrap-metal",
  "ضایعات پلاستیک": "scrap-plastic",
  "ضایعات کاغذ": "scrap-paper",
  "مواد شیمیایی": "chemicals",
  "مواد اولیه شیمیایی": "chemicals",
  "رنگ": "paints-colors",
  "رنگ و رزین": "paints-colors",
  "مواد پلیمری": "polymer-raw",
  "پلاستیک": "polymer-raw",
  "پلیمر": "polymer-raw",
  "بسته بندی": "cartons",
  "بسته‌بندی": "cartons",
  "کارتن": "cartons",
  "نایلون": "films-nylons",
  "نایلون و پلاستیک": "films-nylons",
  "چاپ": "labels-print",
  "لیبل": "labels-print",
  "چاپ و لیبل": "labels-print",
  "ظروف یکبار مصرف": "disposables",
  "ظروف یکبارمصرف": "disposables",
  "دام": "live-animals",
  "دام زنده": "live-animals",
  "طیور": "poultry-eggs",
  "تخم مرغ": "poultry-eggs",
  "آبزیان": "aquaculture",
  "ماهی": "aquaculture",
  "کود": "fertilizers",
  "کشاورزی": "fertilizers",
  "سموم": "pesticides",
  "سموم کشاورزی": "pesticides",
  "گلخانه": "greenhouse",
  "تجهیزات گلخانه": "greenhouse",
  "بذر": "seeds-plants",
  "بذر و نهال": "seeds-plants",
  "نهال": "seeds-plants",
  "علوفه": "forage",
  "خوراک دام": "animal-feed",
  "ماشین آلات": "production-machines",
  "ماشین‌آلات": "production-machines",
  "ماشین آلات تولید": "production-machines",
  "تجهیزات": "production-machines",
  "پمپ": "pumps-compressors",
  "کمپرسور": "pumps-compressors",
  "پمپ و کمپرسور": "pumps-compressors",
  "تجهیزات صنعت غذا": "food-industry",
  "جابه جایی مواد": "material-handling",
  "جابه‌جایی": "material-handling",
  "حمل و نقل": "material-handling",
};

// Default fallback (for categories not in the map)
const DEFAULT_MAPPING = "jadid";

module.exports = { BC_TO_IMACH, DEFAULT_MAPPING };
