/**
 * ─── Storage drivers ─────────────────────────────────────────────────────────
 * One tiny interface, two implementations:
 *
 *   • ArvanStorage — S3-compatible object storage (Arvan Cloud, today's
 *     default). Objects are written public-read with immutable cache headers,
 *     so clients load bytes straight from the cloud CDN — the API never
 *     proxies file bodies (خواسته‌ی کاربر: دانلود سریع و بدون توکن).
 *   • LocalStorage — plain disk under UPLOAD_PATH, served by @fastify/static.
 *     Kept so «بعدا با کمترین هزینه قابل سویچ باشه» is literally an env flip
 *     (STORAGE_DRIVER=local), not a rewrite.
 *
 * The driver surface is deliberately minimal (put/delete) so adding S3, MinIO,
 * B2, … later is one file. The File table stores storageKey, so a provider
 * switch never orphans rows — old provider keys keep deleting.
 */

import { DeleteObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { mkdir, writeFile, unlink } from "node:fs/promises";
import { join } from "node:path";
import { env, storage } from "../common/config/env";

export interface StorageDriver {
  /** Store bytes; returns the public direct URL. */
  put(key: string, body: Buffer, contentType: string): Promise<string>;
  /** Best-effort delete — callers treat storage errors as non-blocking. */
  delete(key: string): Promise<void>;
}

// ─── Arvan (S3-compatible) ───────────────────────────────────────────────────

class ArvanStorage implements StorageDriver {
  private readonly client: S3Client;
  private readonly bucket: string;
  /** Base for public URLs — bucket already included. */
  private readonly publicBase: string;

  constructor() {
    const { ARVAN_ENDPOINT, ARVAN_REGION, ARVAN_ACCESS_KEY, ARVAN_SECRET_KEY, ARVAN_BUCKET_NAME } = storage;
    if (!ARVAN_ENDPOINT || !ARVAN_ACCESS_KEY || !ARVAN_SECRET_KEY || !ARVAN_BUCKET_NAME) {
      throw new Error("STORAGE_DRIVER=arvan but ARVAN_* credentials are missing");
    }

    // ARVAN_ENDPOINT may be virtual-hosted (bucket in the host, e.g.
    // https://<bucket>.s3.<region>.arvanstorage.ir) or the plain API endpoint.
    // The AWS SDK with forcePathStyle always appends the bucket as a path
    // segment, so the API endpoint must NOT contain the bucket — but the
    // public URL keeps whatever shape the account uses.
    const url = new URL(ARVAN_ENDPOINT);
    const bucketHosted = url.hostname.startsWith(`${ARVAN_BUCKET_NAME}.`);
    const apiHost = bucketHosted ? url.hostname.slice(ARVAN_BUCKET_NAME.length + 1) : url.hostname;
    this.bucket = ARVAN_BUCKET_NAME;
    this.publicBase = bucketHosted
      ? `${url.protocol}//${url.hostname}`.replace(/\/$/, "")
      : `${url.protocol}//${url.hostname}/${ARVAN_BUCKET_NAME}`.replace(/\/+$/, "");

    this.client = new S3Client({
      endpoint: `${url.protocol}//${apiHost}`,
      region: ARVAN_REGION || "us-east-1",
      credentials: { accessKeyId: ARVAN_ACCESS_KEY, secretAccessKey: ARVAN_SECRET_KEY },
      forcePathStyle: true,
    });
  }

  async put(key: string, body: Buffer, contentType: string): Promise<string> {
    await this.client.send(
      new PutObjectCommand({
        Bucket: this.bucket,
        Key: key,
        Body: body,
        ContentType: contentType,
        ACL: "public-read",
        CacheControl: "public, max-age=31536000, immutable",
      })
    );
    return `${this.publicBase}/${key}`;
  }

  async delete(key: string): Promise<void> {
    await this.client.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: key }));
  }
}

// ─── Local disk ──────────────────────────────────────────────────────────────

class LocalStorage implements StorageDriver {
  private readonly root: string;
  private readonly base: string;

  constructor() {
    this.root = storage.UPLOAD_PATH;
    // In dev the API origin is enough; behind a proxy set PUBLIC_BASE_URL.
    this.base = `${(storage.PUBLIC_BASE_URL || `http://localhost:${env.PORT}`).replace(/\/$/, "")}/uploads`;
  }

  private path(key: string): string {
    // keys are generated by us (no user input) — still, refuse traversal
    if (key.includes("..")) throw new Error("invalid storage key");
    return join(this.root, key);
  }

  async put(key: string, body: Buffer, _contentType: string): Promise<string> {
    const file = this.path(key);
    await mkdir(file.slice(0, file.lastIndexOf("/")), { recursive: true });
    await writeFile(file, body);
    return `${this.base}/${key}`;
  }

  async delete(key: string): Promise<void> {
    try {
      await unlink(this.path(key));
    } catch {
      /* already gone — fine */
    }
  }
}

/** Built once at boot; STORAGE_DRIVER=arvan without credentials fails fast. */
export function buildStorage(): StorageDriver {
  return storage.DRIVER === "local" ? new LocalStorage() : new ArvanStorage();
}
